version: "3.9"
services:
    elasticsearch:
        container_name: mida-search-es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
        environment:
            - "discovery.type=single-node"
            # password
            - ELASTIC_PASSWORD=elastic123
            - xpack.security.authc.anonymous.roles=superuser
            - xpack.security.authc.anonymous.authz_exception=true
            - xpack.security.enabled=true
            - xpack.security.http.ssl.enabled=false
            # config memory: 4g
            - ES_JAVA_OPTS=-Xms4g -Xmx4g
        networks:
            - mida-search-net
        ports:
            - 9200:9200
        volumes:
            - ./data/elasticsearch:/usr/share/elasticsearch/data
    kibana:
        container_name: mida-search-kb
        image: docker.elastic.co/kibana/kibana:7.11.0
        environment:
            - ELASTICSEARCH_HOSTS=http://mida-search-es:9200
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=elastic123
            - KIBANA_SYSTEM_PASSWORD=kibana123
        networks:
            - mida-search-net
        depends_on:
            - elasticsearch
        ports:
            - 5601:5601
        volumes:
            - ./data/kibana:/usr/share/kibana/data
networks:
    mida-search-net:
        driver: bridge
